-- flowcode no longer owns a database.
--
-- Its boards live in the shared `arcade` D1 alongside wordle, minesweeper and
-- 2048: one `scores` table keyed (game, board, player), where game is
-- 'flowcode' and board is '<mode>-<day>', e.g. 'time-20260721'. The table
-- sorts ascending, so a row stores the negated run score and keeps the real
-- points in `detail` with wpm, accuracy, words, combo and flow.
--
-- The schema itself is maintained in the site repo:
--   https://github.com/Maybaah/Maybaah.github.io -> worker/schema.sql
--
-- This Worker still runs the replay, because that needs this game's word
-- engine (../js/verify.js, ../js/stats.js). Only the storage moved.
